packages:
  - apps/*
  - packages/*

catalog:
  better-auth: 1.3.30

ignoredBuiltDependencies:
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - sharp
