import type { ModelDefinition } from "@/models.js";

export const ollamaModels = [
	{
		id: "llama3.3",
		name: "Llama 3.3 70B",
		family: "meta",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "llama3.3",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen2.5",
		name: "Qwen 2.5",
		family: "alibaba",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "qwen2.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-r1-ollama",
		name: "DeepSeek R1 (Ollama)",
		family: "deepseek",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "deepseek-r1",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama3.2-vision",
		name: "Llama 3.2 Vision",
		family: "meta",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "llama3.2-vision",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "mistral-ollama",
		name: "Mistral (Ollama)",
		family: "mistral",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "mistral",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gemma2-ollama",
		name: "Gemma 2 (Ollama)",
		family: "google",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "gemma2",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "phi4-ollama",
		name: "Phi-4 (Ollama)",
		family: "microsoft",
		free: true,
		providers: [
			{
				providerId: "ollama",
				modelName: "phi4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 16384,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
